<a href="https://colab.research.google.com/github/Salvini126/informatica/blob/main/Esercizio_MongoDBz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pymongo

In [ ]:
# stringa di connessione 3.4 recuperata da Atlas https://www.mongodb.com/cloud/atlas/register
client = pymongo.MongoClient(
    "mongodb://webUser:xxx123xxx@cluster0-shard-00-00.algwo.mongodb.net:27017,cluster0-shard-00-01.algwo.mongodb.net:27017,cluster0-shard-00-02.algwo.mongodb.net:27017/?ssl=true&replicaSet=atlas-am4cb3-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.sample_airbnb # nome del database

In [ ]:
import pandas as pd

In [ ]:
doc = db.listingsAndReviews.find_one()
doc

{'_id': '10082422',
 'access': 'Ideal couple or 2 friends.',
 'accommodates': 2,
 'address': {'country': 'Spain',
  'country_code': 'ES',
  'government_area': "la Dreta de l'Eixample",
  'location': {'coordinates': [2.16942, 41.40082],
   'is_location_exact': True,
   'type': 'Point'},
  'market': 'Barcelona',
  'street': 'Barcelona, Catalunya, Spain',
  'suburb': 'Eixample'},
 'amenities': ['Internet',
  'Wifi',
  'Kitchen',
  'Elevator',
  'Heating',
  'Washer',
  'Shampoo',
  'Hair dryer',
  'Iron',
  'Laptop friendly workspace'],
 'availability': {'availability_30': 0,
  'availability_365': 0,
  'availability_60': 0,
  'availability_90': 0},
 'bathrooms': Decimal128('1.0'),
 'bed_type': 'Real Bed',
 'bedrooms': 1,
 'beds': 2,
 'calendar_last_scraped': datetime.datetime(2019, 3, 8, 5, 0),
 'cancellation_policy': 'flexible',
 'cleaning_fee': Decimal128('10.00'),
 'description': "Hi!  Cozy double bed room in amazing flat next to Passeig de Sant Joan and to metro stop Verdaguer. 3 streets to Sagrada Familia and 4 streets to Passeig de Gracia. Flat located in the center of the city.  View to Sagrada Familia and Torre Agbar. Nice flat in the central neighboorhood of Eixample. Ideal couple or 2 friends. Dreta de l'Eixample",
 'extra_people': Decimal128('0.00'),
 'guests_included': Decimal128('1'),
 'host': {'host_about': "I'm Anna, italian. I'm 28, friendly and easygoing.  I love travelling, reading, dancing tango. Can wait to meet new people! :)",
  'host_has_profile_pic': True,
  'host_id': '30393403',
  'host_identity_verified': False,
  'host_is_superhost': False,
  'host_listings_count': 1,
  'host_location': 'Barcelona, Catalonia, Spain',
  'host_name': 'Anna',
  'host_neighbourhood': "Dreta de l'Eixample",
  'host_picture_url': 'https://a0.muscache.com/im/users/30393403/profile_pic/1427876639/original.jpg?aki_policy=profile_x_medium',
  'host_thumbnail_url': 'https://a0.muscache.com/im/users/30393403/profile_pic/1427876639/original.jpg?aki_policy=profile_small',
  'host_total_listings_count': 1,
  'host_url': 'https://www.airbnb.com/users/show/30393403',
  'host_verifications': ['phone', 'facebook']},
 'house_rules': '',
 'images': {'medium_url': '',
  'picture_url': 'https://a0.muscache.com/im/pictures/aed1923a-69a6-4614-99d0-fd5c8f41ebda.jpg?aki_policy=large',
  'thumbnail_url': '',
  'xl_picture_url': ''},
 'interaction': '',
 'last_scraped': datetime.datetime(2019, 3, 8, 5, 0),
 'listing_url': 'https://www.airbnb.com/rooms/10082422',
 'maximum_nights': '9',
 'minimum_nights': '1',
 'name': 'Nice room in Barcelona Center',
 'neighborhood_overview': "Dreta de l'Eixample",
 'notes': '',
 'number_of_reviews': 0,
 'price': Decimal128('50.00'),
 'property_type': 'Apartment',
 'review_scores': {},
 'reviews': [],
 'room_type': 'Private room',
 'security_deposit': Decimal128('100.00'),
 'space': 'Nice flat in the central neighboorhood of Eixample.',
 'summary': 'Hi!  Cozy double bed room in amazing flat next to Passeig de Sant Joan and to metro stop Verdaguer. 3 streets to Sagrada Familia and 4 streets to Passeig de Gracia. Flat located in the center of the city.  View to Sagrada Familia and Torre Agbar.',
 'transit': ''}

In [ ]:
df1 = pd.DataFrame(list(db.listingsAndReviews.find()))
df1.head(2)

        _id  ... reviews_per_month
0  10082422  ...               NaN
1  10006546  ...               NaN

[2 rows x 42 columns]

Estrarre dalla collection le informazioni richieste:

In [ ]:
# gli appartamenti che costano più di 100 $ a notte

In [ ]:
df2 = pd.DataFrame(list(db.listingsAndReviews.find({"price": {'$gt' : 100 }})))
df2.head(1)

        _id  ... reviews_per_month
0  10051164  ...               NaN

[1 rows x 42 columns]

In [ ]:
# gli appartamenti che costano tra i 100 $ e i 200 $ a notte

In [ ]:
df3 = pd.DataFrame(list(db.listingsAndReviews.find({"price": {'$gt' : 100, '$lt' : 200}})))
df3.head(1)

        _id  ... reviews_per_month
0  10066928  ...               NaN

[1 rows x 42 columns]

In [ ]:
# gli appartamenti che hanno almeno 5 posti letto e che costano tra i 50 $ e 100 $ a notte

In [ ]:
df4 = pd.DataFrame(list(db.listingsAndReviews.find({"$and" : [{"price" : {'$gt' : 50, '$lt' : 100}}, {"beds" : {'$gt' : 5 }}]})))
df4.head(1)

       _id                           listing_url  ... weekly_price monthly_price
0  1111410  https://www.airbnb.com/rooms/1111410  ...          NaN           NaN

[1 rows x 41 columns]

In [ ]:
# gli appartamenti in Portogallo

In [ ]:
df5 = pd.DataFrame(list(db.listingsAndReviews.find({'address.country_code' : 'PT'})))
df5.head(1)

        _id  ... reviews_per_month
0  10006546  ...               NaN

[1 rows x 42 columns]

In [ ]:
# gli appartamenti che non si trovano in Portogallo e in Spagna

In [ ]:
df6 = pd.DataFrame(list(db.listingsAndReviews.find({"address.country_code": {'$not' : {"$in": ["PT", "ES"]}}})))
df6.head(1)

        _id  ... reviews_per_month
0  10021707  ...               NaN

[1 rows x 42 columns]

In [ ]:
# gli appartamenti negli Stati Uniti che hanno il wifi
# ordinare in ordine decrescente sul prezzo per notte e prendere solo i primi 10 appartamenti

In [ ]:
df7 = pd.DataFrame(list(db.listingsAndReviews.find({"amenities": {"$in": ["US"]}})))

SyntaxError: ignored

In [ ]:
# il numero di appartamenti in Portogallo

In [ ]:
# il numero di appartamenti nelle varie nazioni

In [ ]:
# le nazioni con più di 600 appartamenti

In [ ]:
# gli appartamenti che hanno la parola 'beach' nella descrizione (google it...)